language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"
# command to install dependencies
install:
  - pip install -e .
  - pip uninstall nationstates --yes
  - pip install pip-autoremove
  - pip-autoremove nationstates -y
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-pep8
# command to run tests
script:
  py.test tests --pep8

